XXXX = a.out

CXXFLAGS = -Wall -Wextra -Werror -std=c++98

CC = c++

SRC = main.cpp \

OBJ = $(SRC:.cpp=.o)

all: $(XXXX)

$(XXXX): $(OBJ) header.hpp
	$(CC) $(CXXFLAGS) $(OBJ) -o $(XXXX)

%.o: %.cpp 
	$(CC) $(CXXFLAGS) -c $< -o $@

clean:
	rm -rf $(OBJ)

fclean: clean
	rm -rf $(XXXX)

re: fclean all
